name: Deploy .NET Web MVC to Azure Web App (CD)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mvc-frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mvc-frontend/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend/AirportAutomation.sln 
        
      - name: Build
        run: dotnet build ./backend/AirportAutomation.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./backend/AirportAutomation.sln --configuration Release --no-build --verbosity normal

      - name: dotnet publish (Targeting Web Mvc)
        run: dotnet publish ./mvc-frontend/AirportAutomationWeb/AirportAutomation.Web.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-web
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      id-token: write
      contents: read
      
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-web
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'airport-automation-mvc'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_MVC_PUBLISH_PROFILE }}
